### ISSUE TITLE
If a metric is met, it does not indicate the underlying *quality* of that metric.

### ISSUE THREAD

**Issue by RocketD0g** [Air-Quality-Data-Gaps/opportunity-score#1]
Sebastian Diez left a very good comment after the NCAR talk, 

"One issue that worries me is that there are countries like mine (Argentina) where there is national regulation, however this year it turned 50 years old.

Something similar happens with monitoring capabilities, which in some cases are very poor and operate without any QA/QC."

We should include this sort of limitation in the Opportunity Score methodology section -- and also it reinforces the idea of focusing on _bands_ of opportunity, rather than precise scoring, given the imprecision that such unitless scores or indices often have.

**Comment by nishkasharma** [comment]
Closing this issue as it has now been included in the methodology document
