### ISSUE TITLE
Cut off of low-pollution places and/or more heavily weighting PM2.5 metric? 

### ISSUE THREAD

**Issue by RocketD0g** [Air-Quality-Data-Gaps/opportunity-score#4]
I'm seeing that places with super, super low outdoor PM2.5 (like ~5ug/m3 or lower) are ranking above places like Cameroon. We could decide to set a threshold for a place gets a total zero (e.g. Spratly Islands w/ 0? PM2.5 concentration prob automatically should get demoted to the "low opp" list....but could also see starting to fine tune our score (e.g. double or triple the weighting on PM.25 and/or population, for example). I suggest we add in all metrics we think we will use before we start fine tuning, but saying outloud.

**Comment by RocketD0g** [comment]
Related to this - thinking removing countries < 0.5M population.

**Comment by nishkasharma** [comment]
Closing this issue as we wrapped this up last week
